region           = "us-west-2"
user_name        = "example-user"
group_name       = "example-group"
user_policy_arn  = "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
group_policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
